#!/usr/bin/env bash
# ─── deploy-pages.sh ───────────────────────────────────────────────────────
# Manually deploy generated static assets to GitHub Pages.
# Use this when you want to update the panel/sub/geo files WITHOUT running
# the full proxy (e.g. after a successful run, or to push manually).
#
# Usage:
#   export GH_TOKEN=github_pat_xxx
#   ./deploy-pages.sh
#
# Or with a custom Pages URL (default: auto-detect from git remote):
#   export PAGES_URL=https://yourname.github.io/gayroxy
#   ./deploy-pages.sh
#
# Requirements: git, gh CLI (authenticated)
# ────────────────────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; NC='\033[0m'
log()   { echo -e "${GRN}[deploy]${NC} $1"; }
warn()  { echo -e "${YEL}[deploy] WARNING${NC} $1"; }
error() { echo -e "${RED}[deploy] ERROR${NC} $1"; }

# ─── Discover repo info ────────────────────────────────────────────────────
REPO_URL=$(git remote get-url origin 2>/dev/null || true)
if [[ -z "$REPO_URL" ]]; then
    error "Not a git repo or no remote 'origin'"
    exit 1
fi

# Extract owner/name from git remote
if [[ "$REPO_URL" =~ github\.com[:/]([^/]+)/([^/.]+)(\.git)?$ ]]; then
    REPO_OWNER="${BASH_REMATCH[1]}"
    REPO_NAME="${BASH_REMATCH[2]}"
else
    error "Could not parse GitHub remote: $REPO_URL"
    exit 1
fi

# Determine Pages URL
PAGES_URL="${PAGES_URL:-https://${REPO_OWNER}.github.io/${REPO_NAME}}"

log "Repository: ${REPO_OWNER}/${REPO_NAME}"
log "Pages URL:  ${PAGES_URL}"

# ─── Check gh auth ─────────────────────────────────────────────────────────
if ! gh auth status 2>/dev/null; then
    if [[ -n "${GH_TOKEN:-}" ]]; then
        echo "$GH_TOKEN" | gh auth login --with-token 2>/dev/null || true
    fi
    if ! gh auth status 2>/dev/null; then
        error "Not authenticated with GitHub. Set GH_TOKEN or run 'gh auth login'."
        exit 1
    fi
fi

# ─── Source directory for generated files ───────────────────────────────────
# Files generated by proxy.sh live in sub/ and geo/ directories.
# If they don't exist yet, we'll build a minimal set from templates.
BUILD_DIR=$(mktemp -d)
trap "rm -rf \"$BUILD_DIR\"" EXIT

# If the proxy already ran, use its output
if [[ -d "sub" ]]; then
    log "Using existing sub/ directory"
    cp -r sub/* "$BUILD_DIR/" 2>/dev/null || true
fi
if [[ -d "geo" ]]; then
    log "Using existing geo/ directory"
    cp -r geo/ "$BUILD_DIR/" 2>/dev/null || true
fi

# ─── Render templates if no generated files exist ──────────────────────────
if [[ ! -f "$BUILD_DIR/panel.html" ]] && [[ -f "templates/panel.html.tmpl" ]]; then
    log "No rendered panel found — rendering templates with fallback values..."
    export DOMAIN="${DOMAIN:-example.com}"
    # Build minimal DATA for panel preview
    export DATA=$(python3 -c "
import json, os
keys = [
    'VLESS_URL','TROJAN_URL','VMESS_URL','VLESS_GRPC_URL','TROJAN_GRPC_URL',
    'SS_URL','SS_WS_URL','SS_GRPC_URL','VMESS_GRPC_URL',
    'VLESS_HU_URL','TROJAN_HU_URL','VMESS_HU_URL',
    'REALITY_LOCAL_URL','SOCKS5_URL','HTTP_URL',
    'UUID_VLESS','UUID_VMESS','UUID_VLESS_GRPC','UUID_REALITY',
    'TROJAN_PASS','SS_PASS',
    'PATH_VLESS','PATH_TROJAN','PATH_VMESS','PATH_VLESS_GRPC','PATH_TROJAN_GRPC',
    'PATH_SS_WS','PATH_SS_GRPC','PATH_VMESS_GRPC',
    'PATH_VLESS_HU','PATH_TROJAN_HU','PATH_VMESS_HU',
    'GRPC_SERVICE_VLESS','GRPC_SERVICE_TROJAN','GRPC_SERVICE_SS','GRPC_SERVICE_VMESS',
    'PORT_SHADOWSOCKS','PORT_REALITY','PORT_SOCKS5','PORT_HTTP_PROXY',
    'REALITY_PUBLIC','SUB_B64','DOMAIN','PAGES_URL',
    'EXTERNAL_SUB_URLS','EXTERNAL_SUB_COUNT','GAYROXY_SUB_COUNT','TOTAL_SUB_COUNT',
]
d = {k: os.environ.get(k, k.lower() + '_placeholder') for k in keys}
print(json.dumps(d))
")
    envsubst '${DATA} ${DOMAIN} ${PAGES_URL}' < templates/panel.html.tmpl > "$BUILD_DIR/panel.html"
    envsubst '${DOMAIN} ${PAGES_URL}' < templates/index.html.tmpl > "$BUILD_DIR/index.html"
    log "Templates rendered (with placeholder config data)"
fi

# Ensure there's at least something to deploy
if [[ -z "$(ls -A "$BUILD_DIR" 2>/dev/null)" ]]; then
    warn "No content to deploy (sub/ directory empty, no templates)"
    echo "Tip: Run proxy.sh first, or create some content in sub/ and geo/"
    exit 0
fi

# ─── Deploy to gh-pages branch ─────────────────────────────────────────────
log "Deploying to gh-pages branch..."

cd "$BUILD_DIR"
touch .nojekyll

git init
git checkout -b gh-pages
git config user.name "deploy-pages"
git config user.email "deploy@localhost"
git add -A

if git diff --cached --quiet; then
    log "No changes to deploy — content is identical to previous deploy."
    exit 0
fi

git commit -m "🌐 Update panel & assets [manual deploy $(date +%Y-%m-%d_%H:%M)]"

# Push using gh API (no need to manage SSH keys)
TMP_REMOTE="${BUILD_DIR}/_remote"
git remote add origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO_OWNER}/${REPO_NAME}.git" 2>/dev/null || \
    git remote add origin "https://github.com/${REPO_OWNER}/${REPO_NAME}.git"

if git push -f origin gh-pages 2>&1; then
    log "✅ Deployed to ${PAGES_URL}"
else
    error "Push failed. Ensure GH_TOKEN has repo + contents:write scope."
    exit 1
fi